<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<div class="container">

    <?=\Library\Session::getFlash()?>

<form method="post">
    ID :<input type="" name="id" value="<?=$request->get('id')?>" disabled><br>

    
    Comment :<textarea name="comment" class="form-control"  rows="5"><?=$comment->getComment()?></textarea>
    Is active? : <?=$comment->getActive()?><br>
		<input type="radio" name="good" value="0"> Choose this to deactivae comemnt!<br>
        <input type="radio" name="good" value="1">Choose this to make comment be an active!<br>

    <button>SAVE</button>
    
</form>

</div>
</body>
</html>

