<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
<div class="container">

    <?=\Library\Session::getFlash()?>

<form method="post">
    ID :<input type="" name="id" value="<?=$request->get('id')?>" disabled><br>
    
    Comment :<textarea name="comment" class="form-control"  rows="5"><?=$comment->getComment()?></textarea>
    Is active? : <select name="active">
                    <option value="0">Not active</option>
                    <option value="1">Active</option>
               </select><br><br>

    <button>SAVE</button>
    
</form>

</div>
</body>
</html>

