<table width='100%'>
    <tr>
        <th>Uniq ID</th>
        <th>Book id</th>
        <th>Comment</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($comments as $book) : ?>
    <tr>
        <td>
            <?=$book->getId();?>
            <hr>
        </td>
        <td>
            <?=$book->getBookId();?>
            <hr>
        </td>
        <td >
       	<?=$book->getComment();?>
            
            <hr>
        </td>
        <td>
            <a class="btn btn-primary btn-xs" href="/admin/comment/edit/<?=$book->getId()?>">Edit... </a>
            
            <a class="btn btn-danger btn-xs" href="/admin/comment/delete/<?=$book->getId()?>">Delete</a><br><br>
           
           
        </td>
    </tr>
    <?php endforeach; ?>
</table>


