<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    
    <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>
   </head>


  <body>

     <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-5">
          <img style="margin-left: 160px;" class="img-responsive" src="https://s-media-cache-ak0.pinimg.com/564x/66/2c/8c/662c8c3051ca1c941c9d0b8e6dee9863.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>Horror Books</h2>

          <p>
      			<?php foreach($first as $horror) : ?> 
      			<?php echo '<li class="list-group-item">'; ?>
            <img style="margin-left: 160px;" class="img-responsive" src="https://s-media-cache-ak0.pinimg.com/736x/92/05/a7/9205a7e19b7f1e757bad1bf326b3d09e.jpg" alt="Generic placeholder image" width="140" height="140">
    			  Title : <?=$horror->getTitle() ?><br>
      			<?php if ($horror->getSale() != NULL): ?>
  				Price :<strike><?=$horror->getPrice() ?></strike><br>
  				<i style="background-color: lightgreen">SALE</i> : <?=$horror->getSale()?>
      			<?php else: ?>
  				 Price :<?=$horror->getPrice() ?>
      			<?php endif ?>    			
      			<?php endforeach; ?> 
  		 		<?php echo '</li>'; ?> 	
  		 		
      		<hr>
          </p>
          <p><a style="width: 100%" class="btn btn-primary" href="/horror" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-5">
          <img style="margin-left: 160px" class="img-responsive" src="https://s-media-cache-ak0.pinimg.com/736x/80/1c/42/801c427767fe72c51fcd8bff2bde34fc.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>Books Art</h2>
          <p>

          	<?php foreach($second as $val) : ?> 
      			<?php echo '<li class="list-group-item">'; ?>  
            <img style="margin-left: 160px" class="img-responsive" src="http://andreaslenczyk.com/wp-content/uploads/2017/02/SW_Schmedding_Tropen3469-450x675.jpg" alt="Generic placeholder image" width="140" height="140">    			  
      			Title :<?=$val->getTitle() ?><br>       			
      			<?php if ($val->getSale() != NULL): ?>
  				Price :<strike><?=$val->getPrice() ?></strike><br>
  				<i style="background-color: lightgreen">SALE</i> : <?=$val->getSale()?>
      			<?php else: ?>
  				  Price :<?=$val->getPrice() ?>
      			<?php endif ?>    			
      			<?php endforeach; ?> 
  		 		<?php echo '</li>'; ?> 	 	
      		<hr> 
      		         	
          </p>

          <p><a style="width: 100%" class="btn btn-primary" href="/books" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        
      </div><!-- /.row -->

       

      


      <!-- FOOTER -->
      <footer class="footer" style="margin-top: 30px;">
        <div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="http://img07.deviantart.net/2a6e/i/2014/263/b/f/invoker_by_projectxenix-d7zuh5w.jpg" alt="Chania" width="460" height="345">
        <h3>This is First img with price : <?=$horror->getPrice() ?></h3><br>
        <h3>This is Second img with title : <?=$horror->getTitle() ?></h3>
      </div>

      <div class="item">
        <img src="http://img07.deviantart.net/2a6e/i/2014/263/b/f/invoker_by_projectxenix-d7zuh5w.jpg" alt="Chania" width="460" height="345">
         <h3>This is Second img with price : <?=$val->getPrice() ?></h3><br>
         <h3>This is Second img with title : <?=$val->getTitle() ?></h3>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
      </footer>

    </div><!-- /.container -->


  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="webroot/css/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>


