<h2 style="color: red; text-align: center;"><?=\Library\Session::getFlash()?></h2><hr>
<table width='100%'>
    <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Style</th>
        <th>Sale</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($books as $book) : ?>
    <tr>
        <td>
            <?=$book->getTitle();?>
            <hr>
        </td>
        <td>
            <?=$book->getPrice();?>
            <hr>
        </td>
         <td>
           <?php if ( $book->getStyle() == 1): ?>
               <?php echo "Horror Style" ?>
           <?php else: ?>
            <?php echo "Art Style" ?>
           <?php endif ?>
            <hr>
        </td>
        <td >
        <?php if ($book->getSale() != ''): ?>
            <b><i><?=$book->getSale();?></b></i>
        <?php else: ?>
            <?= "<b>---</b>"?>
        <?php endif ?>
            
            <hr>
        </td>
        <td>
            <a class="btn btn-primary btn-xs" href="/admin/books/edit/<?=$book->getId()?>">Edit... </a>
            
            <a class="btn btn-danger btn-xs" onclick="return confirm('Are you sure?')" href='/admin/book/delete/<?=$book->getId()?>'>Delete</a>
           
           
        </td>
    </tr>
    <?php endforeach; ?>
</table>


