<h1 style="margin-top: 50px;">Orded here</h1>

 <?=Library\Session::getFlash() ;?><br>

<form method="post">
    Name: <input id='name'  class="form-control" type="text" name="name" value="<?=$form->name?>"><br>
    Surname: <input id='surname'  class="form-control" type="text" name="surname" value="<?=$form->surname?>"><br>
    Email: <input id='email' class="form-control" type="email" name="email" value="<?=$form->email?>"><br>
    Phone: <input  id='phone' class="form-control" name="phone" value="<?=$form->phone?>"></input><br>
    <button class="btn btn-success">Go</button>
</form>
