<?php if (empty($_SESSION['user'])) :?> 

<style>
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 50%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 45%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 0px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
<body>
<h1>My cart</h1>
<hr>

<?php foreach ($books as $book): ?>
    <b><?=$book->getId();?></b> - <?=$book->getTitle();?> <br>
<?php endforeach; ?>
<br>

<h2>You are not register? Register below!</h2>

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Register now</button>

<div id="id01" class="modal">
  
  <form class="modal-content animate" action="#" method="post">
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="https://s-media-cache-ak0.pinimg.com/564x/67/1b/35/671b35c70ccaf76d330cb9205d6c75a5.jpg" alt="Avatar" class="avatar">
    </div>

    <div class="container">
      <label><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="uname" required><br>

      <label><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>
        
      <button type="submit">Login</button>
      
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>
</html>

<?php else: ?>
    <h1>My cart</h1>
    <?php if (!empty($_COOKIE['books'])): ?>
        <h2>Make an order <a href="/cart/order"><span class="glyphicon glyphicon-thumbs-up"></span></a></h2>
    <?php endif ?>

    <?php if (!empty($_COOKIE['books'])): ?>
        <h3>Clear cart <a href="/cart/delete/" onclick="return confirm('Are you sure?')"><span class="glyphicon glyphicon-trash"></span></a></h3>    
    <?php endif ?>
    
    
<hr>
   

    <?php foreach ($books as $book): ?>

          <div class="col-md-3">
            <div class="thumbnail" style="height:420px;">
                <img class="img-responsive" src="http://d39kbiy71leyho.cloudfront.net/wp-content/uploads/2016/05/09170020/cats-politics-TN.jpg"></img>
                <div class="caption">
                    <h3><?=$book->getTitle()?></h3>
                    <p><?=$book->getPrice()?></p>

                    <p><?php if ( $book->getSale() != null): ?>
                         <p><b>Sale </b>: <?=$book->getSale()?></p>
                    <?php endif ?></p>


                    <p><b>ID:</b> <?=$book->getId()?></p>
                </div>
            </div>
        </div>

    <?php endforeach; ?>
    <br>
<?php endif;?>
 



